POST http://localhost:80/bug/createbug
Content-Type: application/json

{
    "name": "test2963229999",
    "description": "yoooooooo",
    "Creator": "Karl",
    "Collaborators": [
        "Cole",
        "Ali",
        "Tim",
        "Jonathan"
    ],
    "startDateTime": "1992-12-03T13:18:00",
    "endDateTime": "1998-01-09T16:31:00",
    "status": 0,
    "LinkedBugs": [
    ],
    "Tags": [
        "backend",
        "Bugmodel"
    ],
    "Severity": 0
} 